"""add_new_fields_v2

Revision ID: cd8506be469d
Revises: fc3d8036285c
Create Date: 2026-07-03 13:09:11.373043

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cd8506be469d'
down_revision: Union[str, Sequence[str], None] = 'fc3d8036285c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_decisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('internal_code', sa.String(), nullable=True),
    sa.Column('colors', sa.JSON(), nullable=True),
    sa.Column('improvement_notes', sa.Text(), nullable=True),
    sa.Column('improved_golden_sample_expected', sa.Date(), nullable=True),
    sa.Column('decided_at', sa.DateTime(), nullable=True),
    sa.Column('decided_by_id', sa.Integer(), nullable=True),
    sa.Column('decided_by_name', sa.String(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['decided_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id')
    )
    op.add_column('compliance_tracks', sa.Column('name', sa.String(), nullable=False))
    op.add_column('compliance_tracks', sa.Column('initiated_at', sa.DateTime(), nullable=True))
    op.add_column('compliance_tracks', sa.Column('sample_dispatched_at', sa.DateTime(), nullable=True))
    op.add_column('compliance_tracks', sa.Column('expected_delivery_date', sa.Date(), nullable=True))
    op.add_column('compliance_tracks', sa.Column('cert_received_at', sa.DateTime(), nullable=True))
    op.add_column('compliance_tracks', sa.Column('improvement_notes', sa.Text(), nullable=True))
    op.drop_constraint(op.f('compliance_tracks_workflow_id_key'), 'compliance_tracks', type_='unique')
    op.create_index(op.f('ix_compliance_tracks_workflow_id'), 'compliance_tracks', ['workflow_id'], unique=False)
    op.drop_column('compliance_tracks', 'expected_date')
    op.drop_column('compliance_tracks', 'status')
    op.add_column('golden_details', sa.Column('colour_confirmed', sa.Boolean(), nullable=True))
    op.add_column('golden_details', sa.Column('logo_marking_confirmed', sa.Boolean(), nullable=True))
    op.add_column('golden_details', sa.Column('rating_label_confirmed', sa.Boolean(), nullable=True))
    op.add_column('golden_details', sa.Column('bom_confirmed', sa.Boolean(), nullable=True))
    op.add_column('golden_sample_tracks', sa.Column('requested_at', sa.DateTime(), nullable=True))
    op.add_column('golden_workflows', sa.Column('compliance_not_needed', sa.Boolean(), nullable=True))
    op.add_column('golden_workflows', sa.Column('golden_sample_archived', sa.Boolean(), nullable=True))
    op.add_column('golden_workflows', sa.Column('compliance_archived', sa.Boolean(), nullable=True))
    op.add_column('packaging_tracks', sa.Column('sample_version', sa.Integer(), nullable=True))
    op.add_column('packaging_tracks', sa.Column('sample_dispatched_at', sa.DateTime(), nullable=True))
    op.add_column('packaging_tracks', sa.Column('expected_delivery_date', sa.Date(), nullable=True))
    op.add_column('packaging_tracks', sa.Column('sample_status', sa.String(), nullable=True))
    op.add_column('packaging_tracks', sa.Column('decision', sa.String(), nullable=True))
    op.add_column('packaging_tracks', sa.Column('decision_at', sa.DateTime(), nullable=True))
    op.add_column('packaging_tracks', sa.Column('improvement_notes', sa.Text(), nullable=True))
    op.add_column('packaging_tracks', sa.Column('kld_acknowledged_at', sa.DateTime(), nullable=True))
    op.add_column('packaging_tracks', sa.Column('kld_emailed_to_designer_at', sa.DateTime(), nullable=True))
    op.drop_column('packaging_tracks', 'artwork_rejected_at')
    op.drop_column('packaging_tracks', 'kld_rejected_at')
    op.drop_column('packaging_tracks', 'kld_image_url')
    op.drop_column('packaging_tracks', 'artwork_image_url')
    op.drop_column('packaging_tracks', 'sample_id_received')
    op.drop_column('packaging_tracks', 'artwork_approved_at')
    op.drop_column('packaging_tracks', 'released_at')
    op.drop_column('packaging_tracks', 'sample_received_at')
    op.drop_column('packaging_tracks', 'artwork_started_at')
    op.drop_column('packaging_tracks', 'kld_at')
    op.drop_column('packaging_tracks', 'kld_approved_at')
    op.add_column('products', sa.Column('verdict_remarks', sa.Text(), nullable=True))
    op.add_column('products', sa.Column('urbn_model_no', sa.String(), nullable=True))
    op.add_column('products', sa.Column('factory_sku', sa.String(), nullable=True))
    op.add_column('products', sa.Column('colors', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'colors')
    op.drop_column('products', 'factory_sku')
    op.drop_column('products', 'urbn_model_no')
    op.drop_column('products', 'verdict_remarks')
    op.add_column('packaging_tracks', sa.Column('kld_approved_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('packaging_tracks', sa.Column('kld_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('packaging_tracks', sa.Column('artwork_started_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('packaging_tracks', sa.Column('sample_received_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('packaging_tracks', sa.Column('released_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('packaging_tracks', sa.Column('artwork_approved_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('packaging_tracks', sa.Column('sample_id_received', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('packaging_tracks', sa.Column('artwork_image_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('packaging_tracks', sa.Column('kld_image_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('packaging_tracks', sa.Column('kld_rejected_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('packaging_tracks', sa.Column('artwork_rejected_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('packaging_tracks', 'kld_emailed_to_designer_at')
    op.drop_column('packaging_tracks', 'kld_acknowledged_at')
    op.drop_column('packaging_tracks', 'improvement_notes')
    op.drop_column('packaging_tracks', 'decision_at')
    op.drop_column('packaging_tracks', 'decision')
    op.drop_column('packaging_tracks', 'sample_status')
    op.drop_column('packaging_tracks', 'expected_delivery_date')
    op.drop_column('packaging_tracks', 'sample_dispatched_at')
    op.drop_column('packaging_tracks', 'sample_version')
    op.drop_column('golden_workflows', 'compliance_archived')
    op.drop_column('golden_workflows', 'golden_sample_archived')
    op.drop_column('golden_workflows', 'compliance_not_needed')
    op.drop_column('golden_sample_tracks', 'requested_at')
    op.drop_column('golden_details', 'bom_confirmed')
    op.drop_column('golden_details', 'rating_label_confirmed')
    op.drop_column('golden_details', 'logo_marking_confirmed')
    op.drop_column('golden_details', 'colour_confirmed')
    op.add_column('compliance_tracks', sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('compliance_tracks', sa.Column('expected_date', sa.DATE(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_compliance_tracks_workflow_id'), table_name='compliance_tracks')
    op.create_unique_constraint(op.f('compliance_tracks_workflow_id_key'), 'compliance_tracks', ['workflow_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('compliance_tracks', 'improvement_notes')
    op.drop_column('compliance_tracks', 'cert_received_at')
    op.drop_column('compliance_tracks', 'expected_delivery_date')
    op.drop_column('compliance_tracks', 'sample_dispatched_at')
    op.drop_column('compliance_tracks', 'initiated_at')
    op.drop_column('compliance_tracks', 'name')
    op.drop_table('order_decisions')
    # ### end Alembic commands ###
